baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ellingson Mineral Tech Blog'

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = 'github.com/brianreumere/plague'  # Theme

[frontmatter]
  date = [':filename', ':default']

[markup.goldmark.renderer]
  unsafe= true

[params]
  siteHeaderText = "Ellingson Mineral Tech Blog"
  siteFooterText = "Powered by [Hugo](https://gohugo.io/) and the [plague](https://github.com/brianreumere/plague) theme. Hosted on the Gibson supercomputer ⌨️."

  colors = "gibson"

  [params.hcard]
    avatar = "images/i.jpg"
    fullName = "Eugene Belford"
    pronouns = ["they", "them"]
    nickname = "The Plague"
    city = "New York"
    region = "NY"
    country = "US"
    showLocation = true

    social = [
      { platform = "email", identity = "e.belford@example.net", url_pattern = "mailto:%s" },
      { platform = "github", identity = "brianreumere", url_pattern = "https://github.com/%s" }
    ]
